In [32]:
import pandas as pd
import numpy as np

In [33]:
q_2019 = pd.read_csv('bike-share-2019Q1.csv')
q_2020 = pd.read_csv('bike-share-2020Q1.csv')

In [34]:
q_2019.info()

<class 'pandas.DataFrame'>
RangeIndex: 365069 entries, 0 to 365068
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            365069 non-null  int64
 1   start_time         365069 non-null  str
 2   end_time           365069 non-null  str
 3   bikeid             365069 non-null  int64
 4   tripduration       365069 non-null  str
 5   from_station_id    365069 non-null  int64
 6   from_station_name  365069 non-null  str
 7   to_station_id      365069 non-null  int64
 8   to_station_name    365069 non-null  str
 9   usertype           365069 non-null  str
 10  gender             365069 non-null  str
 11  birthyear          365069 non-null  str
 12  ride_length        365069 non-null  str
 13  day_of_week        365069 non-null  int64
dtypes: int64(5), str(9)
memory usage: 39.0 MB

In [35]:
q_2020.info()

<class 'pandas.DataFrame'>
RangeIndex: 426887 entries, 0 to 426886
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             426887 non-null  str
 1   rideable_type       426887 non-null  str
 2   started_at          426887 non-null  str
 3   ended_at            426887 non-null  str
 4   start_station_name  426887 non-null  str
 5   start_station_id    426887 non-null  int64
 6   end_station_name    426886 non-null  str
 7   end_station_id      426886 non-null  float64
 8   start_lat           426887 non-null  float64
 9   start_lng           426887 non-null  float64
 10  end_lat             426886 non-null  float64
 11  end_lng             426886 non-null  float64
 12  member_casual       426887 non-null  str
 13  ride_length         426887 non-null  str
 14  day_of_week         426887 non-null  int64
dtypes: float64(5), int64(2), str(8)
memory usage: 48.9 MB

In [36]:
q_2019 = q_2019.rename(columns={
'trip_id': 'ride_id',
'bikeid': 'rideable_type',
'start_time': 'started_at',
'end_time': 'ended_at',
'from_station_name': 'start_station_name',
'from_station_id': 'start_station_id',
'to_station_name': 'end_station_name',

'to_station_id': 'end_station_id',
'usertype': 'member_casual'
})

In [37]:
q_2019.info()
q_2020.info()

<class 'pandas.DataFrame'>
RangeIndex: 365069 entries, 0 to 365068
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             365069 non-null  int64
 1   started_at          365069 non-null  str
 2   ended_at            365069 non-null  str
 3   rideable_type       365069 non-null  int64
 4   tripduration        365069 non-null  str
 5   start_station_id    365069 non-null  int64
 6   start_station_name  365069 non-null  str
 7   end_station_id      365069 non-null  int64
 8   end_station_name    365069 non-null  str
 9   member_casual       365069 non-null  str
 10  gender              365069 non-null  str
 11  birthyear           365069 non-null  str
 12  ride_length         365069 non-null  str
 13  day_of_week         365069 non-null  int64
dtypes: int64(5), str(9)
memory usage: 39.0 MB
<class 'pandas.DataFrame'>
RangeIndex: 426887 entries, 0 to 426886
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             426887 non-null  str
 1   rideable_type       426887 non-null  str
 2   started_at          426887 non-null  str
 3   ended_at            426887 non-null  str
 4   start_station_name  426887 non-null  str
 5   start_station_id    426887 non-null  int64
 6   end_station_name    426886 non-null  str
 7   end_station_id      426886 non-null  float64
 8   start_lat           426887 non-null  float64
 9   start_lng           426887 non-null  float64
 10  end_lat             426886 non-null  float64
 11  end_lng             426886 non-null  float64
 12  member_casual       426887 non-null  str
 13  ride_length         426887 non-null  str
 14  day_of_week         426887 non-null  int64
dtypes: float64(5), int64(2), str(8)
memory usage: 48.9 MB

In [38]:
# converting datatypes for concating
q_2019['ride_id'] = q_2019['ride_id'].astype(str)
q_2019['rideable_type'] = q_2019['rideable_type'].astype(str)

In [39]:
#concat two datasets
all_trips = pd.concat([q_2019,q_2020],ignore_index=True)

In [40]:
all_trips = all_trips.drop(columns=['start_lat', 'start_lng', 'end_lat', 'end_lng', 'birthyear', 'gender','tripduration'], errors='ignore')

In [41]:
all_trips.columns

Index(['ride_id', 'started_at', 'ended_at', 'rideable_type',
       'start_station_id', 'start_station_name', 'end_station_id',
       'end_station_name', 'member_casual', 'ride_length', 'day_of_week'],
      dtype='str')

In [42]:
all_trips.head(5)

,ride_id,started_at,ended_at,rideable_type,start_station_id,start_station_name,end_station_id,end_station_name,member_casual,ride_length,day_of_week
0,21742443,01-01-2019 00:04,01-01-2019 00:11,2167,199,Wabash Ave & Grand Ave,84.0,Milwaukee Ave & Grand Ave,Subscriber,00:06:30,3
1,21742444,01-01-2019 00:08,01-01-2019 00:15,4386,44,State St & Randolph St,624.0,Dearborn St & Van Buren St (*),Subscriber,00:07:21,3
2,21742445,01-01-2019 00:13,01-01-2019 00:27,1524,15,Racine Ave & 18th St,644.0,Western Ave & Fillmore St (*),Subscriber,00:13:49,3
3,21742446,01-01-2019 00:13,01-01-2019 00:43,252,123,California Ave & Milwaukee Ave,176.0,Clark St & Elm St,Subscriber,00:29:43,3
4,21742447,01-01-2019 00:14,01-01-2019 00:20,1170,173,Mies van der Rohe Way & Chicago Ave,35.0,Streeter Dr & Grand Ave,Subscriber,00:06:04,3

In [43]:
all_trips.shape

(791956, 11)

In [44]:
len(all_trips)

791956

In [45]:
all_trips.info()

<class 'pandas.DataFrame'>
RangeIndex: 791956 entries, 0 to 791955
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             791956 non-null  str
 1   started_at          791956 non-null  str
 2   ended_at            791956 non-null  str
 3   rideable_type       791956 non-null  str
 4   start_station_id    791956 non-null  int64
 5   start_station_name  791956 non-null  str
 6   end_station_id      791955 non-null  float64
 7   end_station_name    791955 non-null  str
 8   member_casual       791956 non-null  str
 9   ride_length         791956 non-null  str
 10  day_of_week         791956 non-null  int64
dtypes: float64(1), int64(2), str(8)
memory usage: 66.5 MB

In [46]:
all_trips.describe()

       start_station_id  end_station_id    day_of_week
count     791956.000000   791955.000000  791956.000000
mean         204.400294      204.379354       3.990219
std          158.919132      159.323552       1.811246
min            2.000000        2.000000       1.000000
25%           77.000000       77.000000       3.000000
50%          174.000000      174.000000       4.000000
75%          291.000000      291.000000       5.000000
max          675.000000      675.000000       7.000000

In [47]:
#value count in member_casual column
all_trips['member_casual'].value_counts()

member_casual
member        378407
Subscriber    341906
casual         48480
Customer       23163
Name: count, dtype: int64

In [48]:
all_trips['member_casual'] = all_trips['member_casual'].replace({
    'Subscriber': 'member',
    'Customer': 'casual'
    })

In [49]:
#check for reassign
all_trips['member_casual'].value_counts()

member_casual
member    720313
casual     71643
Name: count, dtype: int64

In [53]:
#convert started_at and ended_at as datetime

all_trips['started_at'] = pd.to_datetime(all_trips['started_at'], errors='coerce')
all_trips['ended_at']   = pd.to_datetime(all_trips['ended_at'], errors='coerce')

In [54]:
#add separate columns for date month and day

all_trips['date'] = all_trips['started_at'].dt.date
all_trips['day'] = all_trips['started_at'].dt.day
all_trips['month'] = all_trips['started_at'].dt.month
all_trips['year'] = all_trips['started_at'].dt.year
all_trips['day_of_week'] = all_trips['started_at'].dt.day_name()

In [55]:
#ride_length calculation

all_trips['ride_length'] = (all_trips['ended_at']-all_trips['started_at']).dt.total_seconds()

In [56]:
# Inspect the structure of the columns
print("\nData types after adding date columns and ride_length:\n")
all_trips.info()

Data types after adding date columns and ride_length:

<class 'pandas.DataFrame'>
RangeIndex: 791956 entries, 0 to 791955
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             791956 non-null  str
 1   started_at          351494 non-null  datetime64[us]
 2   ended_at            351484 non-null  datetime64[us]
 3   rideable_type       791956 non-null  str
 4   start_station_id    791956 non-null  int64
 5   start_station_name  791956 non-null  str
 6   end_station_id      791955 non-null  float64
 7   end_station_name    791955 non-null  str
 8   member_casual       791956 non-null  str
 9   ride_length         351384 non-null  float64
 10  day_of_week         351494 non-null  str
 11  date                351494 non-null  object
 12  day                 351494 non-null  float64
 13  month               351494 non-null  float64
 14  year                351494 non-null  float64
dtypes: datetime64[us](2), float64(5), int64(1), object(1), str(6)
memory usage: 90.6+ MB

In [60]:
all_trips['ride_length'].count()

np.int64(351384)

In [61]:
all_trips_v2 = all_trips[(all_trips['start_station_name'] != "HQ QR") & 
                         (all_trips['ride_length'] >=0)].copy()

In [62]:
all_trips_v2['ride_length'].count()

np.int64(349348)

In [ ]:
#descriptive analysis on ride_length
all_trips_v2['ride_length'].describe()

count    3.493480e+05
mean     7.462749e+03
std      1.816200e+05
min      0.000000e+00
25%      3.000000e+02
50%      5.400000e+02
75%      9.000000e+02
max      2.652102e+07
Name: ride_length, dtype: float64

In [64]:
#compare member and casual users
print("\nRide length statistics grouped by member_casual:\n",
all_trips_v2.groupby('member_casual')['ride_length'].agg(['mean', 'median', 'max', 'min']))

Ride length statistics grouped by member_casual:
                        mean  median         max  min
member_casual
casual         39365.635283  1380.0  26521020.0  0.0
member          4416.389994   480.0  26138280.0  0.0

In [65]:
# See the average ride time by each day for members vs casual users
print("\nAverage ride length by member type and day of the week:\n",
all_trips_v2.groupby(['member_casual', 'day_of_week'])['ride_length'].mean())

Average ride length by member type and day of the week:
 member_casual  day_of_week
casual         Friday         41842.195515
               Monday         33623.511794
               Saturday       44735.801615
               Sunday         38833.984962
               Thursday       38493.664122
               Tuesday        43785.498938
               Wednesday      40670.016420
member         Friday          3750.612271
               Monday          4383.822455
               Saturday        4241.326740
               Sunday          5975.926648
               Thursday        4057.546818
               Tuesday         3625.329409
               Wednesday       5240.479759
Name: ride_length, dtype: float64

In [68]:
# ordering the days
days_order = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
all_trips_v2['day_of_week'] = pd.Categorical(all_trips_v2['day_of_week'],
categories=days_order, ordered=True)

all_trips_v2.groupby(['member_casual','day_of_week'])['ride_length'].mean()

member_casual  day_of_week
casual         Sunday         38833.984962
               Monday         33623.511794
               Tuesday        43785.498938
               Wednesday      40670.016420
               Thursday       38493.664122
               Friday         41842.195515
               Saturday       44735.801615
member         Sunday          5975.926648
               Monday          4383.822455
               Tuesday         3625.329409
               Wednesday       5240.479759
               Thursday        4057.546818
               Friday          3750.612271
               Saturday        4241.326740
Name: ride_length, dtype: float64

In [69]:
summary_stats = all_trips_v2.groupby(['member_casual', 'day_of_week']).agg(
number_of_rides=('ride_id', 'count'),
average_duration=('ride_length', 'mean')
).reset_index()

In [70]:
print("\nSummary of rides and duration by rider type and weekday:\n", summary_stats)

Summary of rides and duration by rider type and weekday:
    member_casual day_of_week  number_of_rides  average_duration
0         casual      Sunday             3857      38833.984962
1         casual      Monday             7546      33623.511794
2         casual     Tuesday             2826      43785.498938
3         casual   Wednesday             3654      40670.016420
4         casual    Thursday             3144      38493.664122
5         casual      Friday             6823      41842.195515
6         casual    Saturday             2601      44735.801615
7         member      Sunday            42044       5975.926648
8         member      Monday            52584       4383.822455
9         member     Tuesday            50621       3625.329409
10        member   Wednesday            38561       5240.479759
11        member    Thursday            48859       4057.546818
12        member      Friday            46793       3750.612271
13        member    Saturday            39435       4241.326740

In [ ]:
# Create a .csv file that you will visualize elsewhere
counts = all_trips_v2.groupby(['member_casual',
'day_of_week'])['ride_length'].mean().reset_index()
counts.to_csv('avg_ride_length.csv', index=False)

In [79]:
counts.head(15)

   member_casual day_of_week   ride_length
0         casual      Sunday  38833.984962
1         casual      Monday  33623.511794
2         casual     Tuesday  43785.498938
3         casual   Wednesday  40670.016420
4         casual    Thursday  38493.664122
5         casual      Friday  41842.195515
6         casual    Saturday  44735.801615
7         member      Sunday   5975.926648
8         member      Monday   4383.822455
9         member     Tuesday   3625.329409
10        member   Wednesday   5240.479759
11        member    Thursday   4057.546818
12        member      Friday   3750.612271
13        member    Saturday   4241.326740